Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::aliyun-computenest_quickstart-dataease }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'docs/architecture_ecs_single.png'
        AllowedRegions: []
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: DataEase 是开源的数据可视化分析工具，帮助用户快速分析数据并洞察业务趋势，从而实现业务的改进与优化。DataEase 支持丰富的数据源连接，能够通过拖拉拽方式快速制作图表，并可以方便地与他人分享。
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: aliyun-computenest_quickstart-dataease
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/file/aliyun-computenest_quickstart-dataease.tar.gz'